name: GijinkakunProfile
version: 1.0
main: com.gijinkakun.GijinkakunProfile
api-version: 1.20.6
commands:
  pf:
    description: Gets a players Name, Rank, and basic stats and displays them in the chat.
    usage: /<command> <playerName>